# -*- coding: utf-8 -*-
"""pdf summarizer7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uNw0RTpvWdk6mcGH6mpbMKL5F3ZykNsP
"""

!pip install cohere pypdf

from google.colab import files

uploaded = files.upload()  
pdf_filename = list(uploaded.keys())[0]
print(f"Uploaded: {pdf_filename}")

from pypdf import PdfReader

def extract_text_from_pdf(file_path):
    reader = PdfReader(file_path)
    text = ""
    for page in reader.pages:
        page_text = page.extract_text()
        if page_text:
            text += page_text + "\n"
    return text

pdf_text = extract_text_from_pdf(pdf_filename)
print(f"Total characters extracted: {len(pdf_text)}")
print(pdf_text[:1000])  

import cohere

import streamlit as st
co = cohere.Client(st.secrets["COHERE_API_KEY"])

def summarize_text(text, length="medium"):
    max_chars = 100000
    if len(text) > max_chars:
        text = text[:max_chars]

    prompt = f"""Summarize the following document in {length} form.
Give the summary in clear bullet points followed by a short conclusion.

Document:
{text}
"""

    response = co.chat(
        model="command-r-plus-08-2024",
        message=prompt,
        temperature=0.3
    )
    return response.text

summary = summarize_text(pdf_text, length="medium")
print(summary)

with open("summary.txt", "w") as f:
    f.write(summary)

files.download("summary.txt")

